$(document).ready(function(){
    $(".product-card").owlCarousel({
        margin:10,
        loop:true,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    });
  });